"""Public CircuitGraph v1 API."""

from .canonical import canonicalize_graph, document_hash, exact_isomorphism_key, structural_hash
from .migration import CircuitGraphMigrationError, migrate_circuit_graph_payload
from .adapters import (
    graph_parameter_defaults,
    graph_to_linear_circuit,
    graph_to_topology_candidate,
    linear_circuit_to_graph,
    topology_candidate_to_graph,
)
from .model import (
    CIRCUIT_GRAPH_SCHEMA,
    CIRCUIT_GRAPH_VERSION,
    CircuitGraph,
    ComponentInstance,
    GraphDomain,
    GraphPort,
    ModelRef,
    ModelTerminal,
    Net,
    ParameterBinding,
    ParameterVariable,
    PortTerminal,
    ProvenanceRecord,
    Rating,
    TerminalConnection,
)
from .validation import (
    GraphIssue,
    GraphValidationError,
    GraphValidationReport,
    require_valid_graph,
    validate_circuit_graph,
)
from .primitives import expected_parameters, parameter_unit, primitive_model_ref
from .actions import (
    AddComponent,
    AddFeedback,
    AddFragment,
    ConnectTerminal,
    GraphActionError,
    OpenTerminal,
    RemoveComponent,
    ReplaceModel,
    SplitNet,
    TerminatePort,
)
from .search import (
    CircuitGraphBeamSearcher,
    GraphSearchCertificate,
    GraphSearchPolicy,
    GraphSearchResult,
    GraphSearchState,
    LinearGraphActionGenerator,
    PowerGraphActionGenerator,
    ParetoBeamSearch,
    initial_power_graph_state,
    initial_linear_graph_state,
)

__all__ = [
    "CIRCUIT_GRAPH_SCHEMA",
    "CIRCUIT_GRAPH_VERSION",
    "AddComponent",
    "AddFeedback",
    "AddFragment",
    "ConnectTerminal",
    "CircuitGraph",
    "CircuitGraphMigrationError",
    "ComponentInstance",
    "GraphDomain",
    "GraphActionError",
    "GraphIssue",
    "GraphPort",
    "GraphValidationError",
    "GraphValidationReport",
    "GraphSearchCertificate",
    "GraphSearchPolicy",
    "GraphSearchResult",
    "GraphSearchState",
    "CircuitGraphBeamSearcher",
    "LinearGraphActionGenerator",
    "PowerGraphActionGenerator",
    "ModelRef",
    "ModelTerminal",
    "Net",
    "ParameterBinding",
    "ParameterVariable",
    "PortTerminal",
    "OpenTerminal",
    "ProvenanceRecord",
    "Rating",
    "RemoveComponent",
    "ReplaceModel",
    "SplitNet",
    "TerminalConnection",
    "TerminatePort",
    "canonicalize_graph",
    "document_hash",
    "exact_isomorphism_key",
    "expected_parameters",
    "graph_to_linear_circuit",
    "graph_parameter_defaults",
    "graph_to_topology_candidate",
    "linear_circuit_to_graph",
    "migrate_circuit_graph_payload",
    "parameter_unit",
    "ParetoBeamSearch",
    "primitive_model_ref",
    "require_valid_graph",
    "structural_hash",
    "initial_linear_graph_state",
    "initial_power_graph_state",
    "topology_candidate_to_graph",
    "validate_circuit_graph",
]
