"""Unified design-experience evidence contracts.

The package currently exposes :class:`~circuit_ai.evidence.episode.DesignEpisode`,
the versioned replay unit that records every attempted graph action together
with its structural, simulation, and constraint outcome, plus the conversion
helpers that turn a search certificate or an evaluated candidate into episodes.
"""

from .episode import (
    EPISODE_SCHEMA,
    EPISODE_SCHEMA_VERSION,
    STRUCTURAL_COMPLETE,
    STRUCTURAL_NOT_APPLIED,
    STRUCTURAL_REVERTED,
    STRUCTURAL_VALID,
    DesignEpisode,
    DesignStep,
    EpisodeCandidate,
    EpisodeChainError,
    EpisodeContractError,
    build_candidate_episodes,
    candidate_accepted,
    candidate_failure_category,
    decode_action,
    empty_state_hash,
    encode_action,
    episode_candidate,
    episode_hash,
    load_episodes,
    manifest_hash,
    search_episode,
    search_termination_reason,
    spec_hash_for,
    stable_payload_hash,
    validate_state_chain,
    write_episode_artifact,
    write_episodes,
)

__all__ = [
    "EPISODE_SCHEMA",
    "EPISODE_SCHEMA_VERSION",
    "STRUCTURAL_COMPLETE",
    "STRUCTURAL_NOT_APPLIED",
    "STRUCTURAL_REVERTED",
    "STRUCTURAL_VALID",
    "DesignEpisode",
    "DesignStep",
    "EpisodeCandidate",
    "EpisodeChainError",
    "EpisodeContractError",
    "build_candidate_episodes",
    "candidate_accepted",
    "candidate_failure_category",
    "decode_action",
    "empty_state_hash",
    "encode_action",
    "episode_candidate",
    "episode_hash",
    "load_episodes",
    "manifest_hash",
    "search_episode",
    "search_termination_reason",
    "spec_hash_for",
    "stable_payload_hash",
    "validate_state_chain",
    "write_episode_artifact",
    "write_episodes",
]
